version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: erasmus_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: erasmus_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmq_data:
