# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student_profile.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'student_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15student_profile.proto\x12\x07student\"\'\n\x11GetStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x03\"\x8c\x01\n\x16StudentProfileResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x17\n\x0fhome_university\x18\x05 \x01(\t\x12\x17\n\x0fhost_university\x18\x06 \x01(\t2b\n\x0eStudentService\x12P\n\x11GetStudentProfile\x12\x1a.student.GetStudentRequest\x1a\x1f.student.StudentProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTUDENTREQUEST']._serialized_start=34
  _globals['_GETSTUDENTREQUEST']._serialized_end=73
  _globals['_STUDENTPROFILERESPONSE']._serialized_start=76
  _globals['_STUDENTPROFILERESPONSE']._serialized_end=216
  _globals['_STUDENTSERVICE']._serialized_start=218
  _globals['_STUDENTSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
